### ISSUE TITLE
Admin JSONError

### ISSUE THREAD

**Issue by antoineVIVIES** [kenneth051/drf-history#33]
When i try to connect to django admin with the middleware active it put me this error
![image](https://user-images.githubusercontent.com/23381717/80165931-421c3e00-860f-11ea-99cc-5c3f3a71085c.png)

**Comment by kenneth051** [comment]
@antoineVIVIES let me fix it.

**Comment by kenneth051** [comment]
@antoineVIVIES  issue has been fixed. uninstall your current version and install the new version

**Comment by antoineVIVIES** [comment]
Working perfectly Thanks a lot !
