### ISSUE TITLE
Can't decode images

### ISSUE THREAD

**Issue by DimaSapsay** [kenneth051/drf-history#36]
When I want save image in form, I have this errors:

```
Traceback (most recent call last):
  File "/home/world/.venv/atlas-control-panel-api/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/world/.venv/atlas-control-panel-api/lib/python3.7/site-packages/track_actions/requestMiddleware.py", line 20, in __call__
    self._requestdata["body_data"] = copy.copy(request.body.decode("utf-8"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 419: invalid start byte
```

**Comment by kenneth051** [comment]
hello, Are you using Django rest framework or default Django? This package
was only tested to be used with django rest framework. I am guessing you
might be saving the image in its original form, that is why you're getting
that error. it cannot convert the image to a string

**Comment by tehnuty** [comment]
> hello, Are you using Django rest framework or default Django? This package was only tested to be used with django rest framework. I am guessing you might be saving the image in its original form, that is why you're getting that error. it cannot convert the image to a string
> […](#)

Can confirm this issue is reproducable with DRF as well.

@DimaSapsay the temporary fix for this is to create custom MiddleWare for `track_actions.requestMiddleWare.RequestMiddleware` and skip everything if `Content-Type` is `multipart/form-data`

example:
```python
class RequestMiddleware(track_actions.requestMiddleware.RequestMiddleware):
    def __call__(self, request: Request):
        if request.content_type == "multipart/form-data":
            return self.get_response(request)

        return super().__call__(request)
```

**Comment by kenneth051** [comment]
@tehnuty could you raise a PR for that fix?

**Comment by kenneth051** [comment]
@DimaSapsay A new version has been released with changes from @tehnuty . please confirm if it works for you. thanks.
PS: sorry for the delayed release

**Comment by DimaSapsay** [comment]
@kenneth051 thank you.
