### ISSUE TITLE
unsupported operand type(s) for +: 'PosixPath' and 'str'

### ISSUE THREAD

**Issue by zebuth95** [kenneth051/drf-history#50]
Hello there I'm using Django 3.1.6 and I get this Error using drf-history 1.0.0

yaml_file = open(settings.BASE_DIR + "/drf_history.yaml", "r")
TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'

that I already fix replacing 

yaml_file = open(settings.BASE_DIR + "/drf_history.yaml", "r")
![Screenshot_2021-06-04_10-05-48](https://user-images.githubusercontent.com/22620344/120822920-7ce3eb80-c51c-11eb-8d9b-ecc41f675b93.png)

for

yaml_file = open(os.path.join(settings.BASE_DIR)+"/drf_history.yaml", "r")

**Comment by kenneth051** [comment]
@zebuth95 could you open a PR for it? if you have the time. thanks

**Comment by kenneth051** [comment]
I will look into it

**Comment by kenneth051** [comment]
Issue resolved.
